---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
	collapse = TRUE,
	comment = "#>"
)
```

```{r setup}
library(PDAV)
library(simsam)
library(terra)
library(sf)
library(caret)
library(CAST)
library(dplyr)
library(tidyr)


n_samples <- 100
n_iters <- 10
```


## Prepare simulated data

### Generate predictors and response
```{r}
set.seed(100)

rast_grid <- rast(xmin = 0, xmax = 200, ymin = 0, ymax = 200, ncols = 200, nrows = 200)

grad_predictors <- sim_covariates(rast_grid, vgm = gstat::vgm(psill = 1, model = "Exp", range = 50), n = 8)
landcover <- sim_covariates(
	rast_grid,
	vgm = gstat::vgm(psill = 5, model = "Exp", range = 100),
	n = 2,
	beta = 10,
	indicators = TRUE
)

predictors <- c(grad_predictors, landcover)
names(predictors) <- c("temp", "moisture", "ph", "elev", "slope", "solar", "dist_road", "prod", "forest", "grass")

outcome_pred <- blend_rasters(
	predictors,
	~
		# species/habitat suitability score (unscaled)
		1.2 *
			exp(-((ph - 6.5)^2) / (2 * 0.6^2)) *
			(1 - exp(-moisture / 0.25)) + # pH optimum × moisture saturation
			0.5 * exp(-((temp - 15)^2) / (2 * 5^2)) * exp(-elev / 150) + # mild temp optimum, penalised by elevation
			0.3 * (forest / (1 + exp(-2 * (forest - 0.5)))) -
			0.2 * (grass / (1 + exp(-2 * (grass - 0.5)))) +
			0.05 * slope
	# forest boosts, grass reduces, small slope term
)

plot(outcome_pred)

noise <- sim_covariates(rast_grid, vgm = gstat::vgm(psill = 0.001, model = "Exp", range = 10), n = 1)
names(noise) <- "noise"
outcome <- outcome_pred + noise
plot(outcome)


r <- c(predictors, outcome)
terra::crs(r) <- "EPSG:3857"

ppoints <- spatSample(r, size = 1000, method = "regular", na.rm = TRUE, as.points = TRUE) |>
	st_as_sf()

response_name <- "outcome"
predictor_names <- names(predictors)
plot(c(noise, r))
```

### Generate samples

```{r}
set.seed(100)

samples <- lapply(1:n_iters, function(i) {
	sample_random <- sam_field(
		x = r,
		size = n_samples,
		type = "random",
		na.rm = TRUE
	) |>
		terra::extract(x = r, bind = TRUE) |>
		st_as_sf() |>
		mutate(sampling = "random")

	sample_clustered <- sam_field(
		x = r,
		size = 100,
		type = "clustered",
		type_opts = list(nclusters = 5, radius = 15),
		na.rm = TRUE
	) |>
		terra::extract(x = r, bind = TRUE) |>
		st_as_sf() |>
		mutate(sampling = "clustered")

	rbind(sample_random, sample_clustered)
})


```


## CV splits
```{r}

folds <- lapply(1:n_iters, function(i) {
	train_points_i <- samples[[i]]

	folds_smpl <- lapply(unique(train_points_i$sampling), function(smpl) {
		train_points <- train_points_i |> filter(sampling == smpl)

		# cluster points based on kmeans
		coords <- sf::st_coordinates(train_points) |> as.matrix()
		clust <- stats::kmeans(x = coords, centers = 10)
		pts_id <- cbind(train_points, clust$cluster)
		pts_id$rand <- sample(c(1:10), nrow(pts_id), replace = TRUE)

		#### Folds based on outcome range
		# Define folds based on 10-fold cluster CV
		folds_spatial <- CAST::CreateSpacetimeFolds(pts_id, spacevar = "clust.cluster", k = 10)
		# Define folds based on kNNDM
		folds_knndm <- knndm(train_points, predpoints = ppoints)
		# Define folds based on NNDM
		folds_nndm <- CAST::nndm(train_points, predpoints = ppoints, min_train = 0.5)

		return(list(
			"folds_spatial_train" = folds_spatial$index,
			"folds_spatial_test" = folds_spatial$indexOut,
			"folds_knndm_train" = folds_knndm$indx_train,
			"folds_knndm_test" = folds_knndm$indx_test,
			"folds_nndm_train" = folds_nndm$indx_train,
			"folds_nndm_test" = folds_nndm$indx_test
		))
	})

	names(folds_smpl) <- unique(train_points_i$sampling)
	folds_smpl
})
```

## Modelling
```{r}
form <- as.formula(paste0("outcome~", paste0(predictor_names, collapse = "+")))
pgrid <- data.frame(mtry = 6)

cv_diff <- lapply(1:n_iters, function(i) {
	train_points_i <- samples[[i]]

	lapply(unique(train_points_i$sampling), function(smpl) {
		traindf <- train_points_i |>
			filter(sampling == smpl) |>
			st_drop_geometry() |>
			select(all_of(c(predictor_names, response_name)))

		folds_i_smpl <- folds[[i]][[smpl]]
		# Validate with random CV and compute metrics
		r_cntrl <- trainControl(method = "CV", savePredictions = TRUE)
		rand_mod <- train(form, data = traindf, method = "rf", trControl = r_cntrl, tuneGrid = pgrid, ntree = 100)
		err_stats_rand <- global_validation(rand_mod)
		rand_stats <- data.frame(
			RMSE = err_stats_rand[[1]],
			MAE = err_stats_rand[[3]],
			R2 = err_stats_rand[[2]],
			method = "randomCV"
		)

		# Compute CV statistics in surface
		surfdf <- terra::as.data.frame(r)
		surfdf$preds <- predict(rand_mod, newdata = surfdf)
		surf_stats <- surfdf %>%
			summarise(
				RMSE = sqrt(mean((outcome - preds)^2)),
				MAE = mean(abs(outcome - preds)),
				R2 = cor(outcome, preds)^2
			)
		names(surf_stats) <- paste0(names(surf_stats), "_surf")

		# Validate with 10-fold cluster CV and compute CV statistics
		spatial_cntrl <- trainControl(
			method = "cv",
			index = folds_i_smpl$folds_spatial_train,
			indexOut = folds_i_smpl$folds_spatial_test,
			savePredictions = TRUE
		)
		spatial_mod <- suppressWarnings(train(
			form,
			data = traindf,
			method = "rf",
			trControl = spatial_cntrl,
			tuneGrid = pgrid,
			ntree = 100
		))
		err_stats_spatial <- global_validation(spatial_mod)
		spatial_stats <- data.frame(
			RMSE = err_stats_spatial[[1]],
			MAE = err_stats_spatial[[3]],
			R2 = err_stats_spatial[[2]],
			method = "spatialCV"
		)

		# Validate with knndm and compute CV statistics
		kndm_cntrl <- trainControl(
			method = "cv",
			index = folds_i_smpl$folds_knndm_train,
			indexOut = folds_i_smpl$folds_knndm_test,
			savePredictions = TRUE
		)
		kndm_mod <- suppressWarnings(train(
			form,
			data = traindf,
			method = "rf",
			trControl = kndm_cntrl,
			tuneGrid = pgrid,
			ntree = 100
		))
		err_stats_kndm <- global_validation(kndm_mod)
		kndm_stats <- data.frame(
			RMSE = err_stats_kndm[[1]],
			MAE = err_stats_kndm[[3]],
			R2 = err_stats_kndm[[2]],
			method = "kNNDM CV"
		)

		# Validate with NNDM LOO and compute CV statistics (outcome range)
		nndm_cntrl <- trainControl(
			method = "cv",
			index = folds_i_smpl$folds_nndm_train,
			indexOut = folds_i_smpl$folds_nndm_test,
			savePredictions = TRUE
		)
		nndm_mod <- suppressWarnings(train(
			form,
			data = traindf,
			method = "rf",
			trControl = nndm_cntrl,
			tuneGrid = pgrid,
			ntree = 100
		))
		err_stats_nndm <- global_validation(nndm_mod)
		nndm_stats <- data.frame(
			RMSE = err_stats_nndm[[1]],
			MAE = err_stats_nndm[[3]],
			R2 = err_stats_nndm[[2]],
			method = "NNDM LOOCV"
		)

		# Tidy and return results
		cv_results <- rbind(rand_stats, spatial_stats, kndm_stats, nndm_stats)
		cbind(cv_results, surf_stats) |>
			mutate("RMSE_diff" = RMSE - RMSE_surf, "MAE_diff" = MAE - MAE_surf, "R2_diff" = R2 - R2_surf) |>
			select(c(method, RMSE_diff, MAE_diff, R2_diff)) |>
			pivot_longer(-method) |>
			mutate(iteration = i, sampling = smpl)
	}) |>
		do.call(what = "rbind")
}) |>
	do.call(what = "rbind") |>
	mutate(sampling = factor(sampling, levels = c("random", "clustered")))


```


## Plot results

```{r}
p <- ggplot(cv_diff |> filter(name == "RMSE_diff"), aes(x = method, y = value)) +
	geom_boxplot() +
	geom_hline(yintercept = 0) +
	facet_wrap(~sampling) +
	theme_bw()
p

ggsave("man/figures/rmse_comp.png", p)
```